### ISSUE TITLE
Problem with WMP Integration - sometimes

### ISSUE THREAD

**Issue by Stamimail** [yfdyh000/PhotoSift#1]
![תמונה](https://user-images.githubusercontent.com/11010156/102620638-f6db1080-4146-11eb-8f55-6b83e0926834.png)

**Comment by yfdyh000** [comment]
Sorry for such a late reply, I just noticed I forgot watch this fork repo...

I see this problem. As of now, you can temporarily fix it by opening and closing the settings window. It may be fixed later.

**Comment by Stamimail** [comment]
Hi, I happy to see the project has an activity again.

**Comment by yfdyh000** [comment]
Fixed in v1.26. https://github.com/yfdyh000/PhotoSift/releases
