### ISSUE TITLE
Virus Gen:Variant.Bulz345451 detected!

### ISSUE THREAD

**Issue by arkdzo** [yfdyh000/PhotoSift#4]
v. 1.25 Release
Virus detected: Gen:Variant.Bulz345451
Virustotal: https://www.virustotal.com/gui/file/4ef010781943cc5a2a7b8b76fb381ac2085812df7ed4a5067d63e9422cf26b90/relations

**Comment by yfdyh000** [comment]
I saw it and there were two AV providers reporting risk. Since I clicked the Rescan, it is now 0/59.
You can trust the project.
